# -*- coding: utf-8 -*-
"""GHG Emissions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10B8Dbr_4qtmaicmD652tJdkFXRLdqEN_
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

df = pd.read_excel("Ghg Per Capita.xlsx")
df

df.isnull().sum()

df.info()

df.shape

df.describe()

df.isnull().sum()/df.shape[0]*100

cols = ['EDGAR Country Code','Country',1970,1971,1972,1973,1974,1975,1976,1977,1978,1979,1980,1981,1982,1983,1984,1985,1986,1987,1988,1989,1990,1991,1992,1993,1994,1995,1996,1997,1998,1999,2000,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022]
for i in cols:
  df[i].fillna("None",inplace=True)

df.info()

print('Country' in df.columns)

print(df.columns)

country_data = df['Country']
print(country_data)

# /////////////////////////

def plot_country_ghg(country):
    country_row = df[df['Country'] == country]
    emissions = country_row.iloc[:, 2:].T  # Transpose to have years as index
    emissions.columns = [country]
    emissions.plot(kind='line', marker='o', figsize=(10, 6))
    plt.title(f'GHG Emissions for {country}')
    plt.xlabel('Year')
    plt.ylabel('GHG Emissions')
    plt.xticks(rotation=45)
    plt.grid()


for country_n in df['Country'].unique():
  plt.figure(figsize=(10, 6))
  plot_country_ghg(country_n) 
  plt.tight_layout()
  plt.show()

def get_ghg_for_country_and_year(country, year):
  try:
    row = df[df['Country'] == country]
    if not row.empty:
      ghg_value = row[year].values[0]
      if ghg_value != 'None':
        return ghg_value
      else:
        return "Data not available for this year and country."
    else:
      return "Country not found in dataset."
  except KeyError:
    return "Invalid Year entered"

country_input = input("Enter the name of the country: ")
year_input = int(input("Enter the year: "))

ghg_emissions = get_ghg_for_country_and_year(country_input, year_input)
print(f"GHG emissions for {country_input} in {year_input}: {ghg_emissions}")